language: android
android:
  components:
    - tools
    - android-23
    - build-tools-23.0.2
    - extra-google-google_play_services
    - extra-google-m2repository
    - extra-android-m2repository
  licenses:
    - '.+'


script: ./gradlew clean assembleProdDebug
